import React from "react";
import "../styles/globals.css";
import type { Metadata } from "next";
import { cls } from "../libs/client/utils";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body>
                <div className={cls(["w-full", "max-w-xl", "mx-auto"])}>{children}</div>
            </body>
        </html>
    );
}
